# Generated by Django 5.0.1 on 2024-03-21 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_backgroud_image", models.ImageField(upload_to="about_images")),
                ("title", models.CharField(max_length=100, unique=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AboutTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("position", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cause_background_image", models.ImageField(upload_to="cause_images")),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "amount_needed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "amount_raised",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "amount_left",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_donations", models.IntegerField(default=0)),
                ("weeks", models.IntegerField(default=0)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChildAbuseReporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("child_name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                (
                    "abuse_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Abuse"),
                            ("emotional", "Emotional Abuse"),
                            ("sexual", "Sexual Abuse"),
                            ("neglect", "Neglect"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("ashanti", "Ashanti Region"),
                            ("brong-ahafo", "Brong-Ahafo Region"),
                            ("central", "Central Region"),
                        ],
                        max_length=50,
                    ),
                ),
                ("town", models.CharField(max_length=100)),
                ("support_needed", models.TextField()),
                ("sub_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.IntegerField()),
                ("content", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[("mr", "Mr"), ("mrs", "Mrs"), ("ms", "Ms")],
                        default="select",
                        max_length=10,
                    ),
                ),
                ("full_name", models.CharField(max_length=155)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "donation_amount",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("online", "Online Payment"),
                            ("cash", "Cash Payment"),
                        ],
                        default="online",
                        max_length=10,
                    ),
                ),
                ("payment_link", models.URLField(blank=True, null=True)),
                ("donation_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Donations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("amount_donated", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image", models.ImageField(upload_to="donations")),
                ("purpose", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_background_image",
                    models.ImageField(default="voc.jpg", upload_to="event_images"),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("title", models.CharField(max_length=155, unique=True)),
                (
                    "short_content",
                    models.CharField(
                        default="Write some something short", max_length=255
                    ),
                ),
                ("full_content", models.TextField(default="No content to read! ")),
            ],
        ),
        migrations.CreateModel(
            name="HomeHeaderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_image", models.ImageField(upload_to="home_header")),
                ("short_content", models.CharField(max_length=100)),
                ("second_image", models.ImageField(upload_to="home_header")),
                ("short_content_2", models.CharField(max_length=100)),
                ("third_image", models.ImageField(upload_to="home_header")),
                ("short_content_3", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_image", models.ImageField(upload_to="home_images")),
                ("short_title", models.CharField(max_length=50)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MissionPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="mission_images")),
            ],
        ),
        migrations.CreateModel(
            name="PicturesGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pictures")),
                ("title", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[("mr", "Mr"), ("mrs", "Mrs"), ("ms", "Ms")],
                        default="select",
                        max_length=5,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, upload_to="profile_pictures/"),
                ),
                ("bio", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideosGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="videos")),
                ("title", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TotalDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_need", models.PositiveIntegerField()),
                ("amount_received", models.PositiveIntegerField()),
                ("amount_left", models.PositiveIntegerField()),
                ("number_of_donations", models.IntegerField(default=0)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.donations"
                    ),
                ),
            ],
        ),
    ]
