# Generated by Django 5.0.1 on 2024-03-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutteam",
            name="image",
            field=models.ImageField(
                default="adebayo.png", upload_to="about_team_images"
            ),
        ),
    ]
