# Generated by Django 5.0.1 on 2024-03-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_aboutteam_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="payment_link",
            field=models.BooleanField(default=False),
        ),
    ]
