# Generated by Django 5.0.1 on 2024-03-23 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_comment_reportabuse_delete_childabusereporter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportabuse",
            name="add_new_abuse_type",
        ),
        migrations.RemoveField(
            model_name="reportabuse",
            name="add_new_region",
        ),
    ]
