# Generated by Django 5.0.6 on 2024-07-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_abusetype_region_alter_reportabuse_abuse_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email1", models.EmailField(max_length=254)),
                ("email2", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=156)),
                ("city", models.CharField(max_length=155)),
            ],
        ),
    ]
